Issue #341: Include checks for graphviz dot dependency
catalyst/moodle-tool_dataflows pull request #371
Opened 2022-07-28 04:45 UTC by jaypha

Resolves #341 

Display warnings if dot not available.
Show alternate icon to dot images.

2022-07-28 04:51 UTC, keevan commented on classes/visualiser.php
> +        } else {
This else block is unnecessary due to the early return. Also caused a bunch of changes to appear in the PR which weren't relevant.

2022-07-28 04:52 UTC, keevan commented on classes/helper.php
> +        }
Please remove the unnecessary else block, due to the early return in the if block.

2022-07-28 04:55 UTC, keevan commented on lang/en/tool_dataflows.php
> +$string['no_dot_installed'] = 'No valid path to Graphviz dot found (Have you installed it?).';
A link to the repository dependency section would be useful here.

e.g. describe the problem that occurred, then show an action so they can fix it.

2022-07-28 04:58 UTC, keevan reviewed
Are you able to also add some screenshots to the PR so I know how it looks?

Thanks Jason.

2022-07-28 04:58 UTC, keevan commented on settings.php
> +
Can you remove the extra whitespace here.

2022-07-28 05:02 UTC, keevan commented on lang/en/tool_dataflows.php
> +$string['no_dot_installed_short'] = 'Graphviz not found';
```suggestion
$string['no_dot_installed_short'] = 'Graphviz not installed';
```
Or perhaps this would be clearer?
```suggestion
$string['no_dot_installed_short'] = 'Graphviz not installed - dot unavailable';
```

2022-07-28 05:24 UTC, jaypha commented on lang/en/tool_dataflows.php
> +$string['no_dot_installed_short'] = 'Graphviz not found';
It could be that the specified path is wrong.

2022-07-28 05:31 UTC, jaypha commented
The main message.
![Screenshot from 2022-07-28 15-27-43](https://user-images.githubusercontent.com/1052990/181427806-1c102095-c011-4582-8bf7-7b75fe07c941.png)
The alternate icons
![Screenshot from 2022-07-28 15-28-15](https://user-images.githubusercontent.com/1052990/181427876-4bef8ffe-6bf6-4eda-a088-7ec121f439c6.png)
The step chooser with name printed next to the icon.
![Screenshot from 2022-07-28 15-28-41](https://user-images.githubusercontent.com/1052990/181427923-06b7d232-553b-4c5c-99c4-04e6bc2668c6.png)

2022-07-28 05:32 UTC, jaypha commented on lang/en/tool_dataflows.php
> +$string['no_dot_installed'] = 'No valid path to Graphviz dot found (Have you installed it?).';
done

2022-07-28 05:33 UTC, jaypha commented on classes/visualiser.php
> +        } else {
done

2022-07-28 05:34 UTC, jaypha commented on classes/helper.php
> +        }
done

2022-07-28 05:34 UTC, jaypha commented on settings.php
> +
done

2022-07-28 10:52 UTC, keevan commented on lang/en/tool_dataflows.php
> +$string['no_dot_installed_short'] = 'Graphviz not found';
Would you be able to make this clearer so the user can tell whether or not they need to install it, or need to fix the path. I think that would be the sweet spot.

2022-07-29 04:50 UTC, keevan requested changes
I think overall the patch looks good. There are few suggestions which should make things clearer for the user to action.

2022-07-29 04:50 UTC, keevan commented on classes/dataflows_table.php
> +            );
Instead of displaying just a :exclamation: , could we have supporting text? This helps with accessibility and generally is better than assuming the user will hover over the img to see the tooltip.

![image](https://user-images.githubusercontent.com/9924643/181683436-bc36a690-76ac-470a-bbab-a580c0c2ffe8.png)

![image](https://user-images.githubusercontent.com/9924643/181683488-8f8815db-e7b3-4044-a3ef-5bc0895da4da.png)

Perhaps something like, "Preview unavailable"

2022-07-29 04:50 UTC, keevan commented on classes/visualiser.php
> +            );
![image](https://user-images.githubusercontent.com/9924643/181683740-c94a327c-55b2-4fa6-b4e6-e1fb2aad04b0.png)

I am of the opinion that third party dependencies for the plugin, e.g. graphviz, should instead be referenced from the latest version of our readme, instead of directly from the error / warning.

Reasons:
- The link might become outdated or changed later on, the user will then be redirected to a broken page, even if we have properly updated it in our readme.
- The plugin readme (since it's hosted on github) should be long standing and up to date, so referencing the dependency here and where to update/download it the ideal middle layer (though I understand the simplicity of going straight to the vendor)
- There might be additional instructions for setting it up, _especially_ to work with our plugin. In this particular instance, it probably isn't too important, but I still believe it's good to have this be standard behaviour for dependencies listed.

I do think the wording can be updated, which falls under the lang string section but since it's related I'll put it here also.

Currently it is:
> No valid path to Graphviz dot found (Have you installed it?). Download Graphviz here.

The suggested version might look like so:
> A dependency "dot" could not be found. View dependencies and installation instructions **here**.

And the link would be either the [dataflows github repository](https://github.com/catalyst/moodle-tool_dataflows), or the [moodle plugins directory](http://moodle.org/plugins). Since this is unpublished, it would lean towards the former.

2022-07-29 06:57 UTC, jaypha commented
![Screenshot from 2022-07-29 16-53-07](https://user-images.githubusercontent.com/1052990/181701373-9136c403-6e4c-4481-836f-75c5e0a21d65.png)

2022-07-29 06:57 UTC, jaypha commented
![Screenshot from 2022-07-29 16-54-02](https://user-images.githubusercontent.com/1052990/181701425-7787d9c9-9508-4a81-b094-98149cd1035d.png)

2022-07-29 06:58 UTC, jaypha commented
I decided to remove the images here altogether (when Graphviz is unavailable), because it was getting too complicated otherwise).

![Screenshot from 2022-07-29 16-54-16](https://user-images.githubusercontent.com/1052990/181701464-c5b624e5-557d-4097-9600-1146e4548334.png)

2022-07-29 06:59 UTC, jaypha commented on classes/dataflows_table.php
> +            );
New screenies follow.

2022-07-29 07:00 UTC, jaypha commented on classes/visualiser.php
> +            );
New screenies below.

2022-08-01 05:05 UTC, keevan commented
Thanks Jason. Those changes do seem better. I'm a bit on the fence about https://github.com/catalyst/moodle-tool_dataflows/pull/371#issuecomment-1198944324

Do you think this message as shown here: https://github.com/catalyst/moodle-tool_dataflows/pull/371#issuecomment-1198944146 should also be put on the details page as well? From a user perspective I would have liked the main "preview unavailable" shown to also mention something about a dependency being missing, even specifically "dot". There's currently no direct correlation between the two and I think there should be, for the user's awareness.

2022-08-01 05:25 UTC, keevan approved these changes

2022-08-01 05:26 UTC, merged