Issue #781: Add config to set webservice step params as lowercase
catalyst/moodle-tool_dataflows pull request #782
Opened 2023-06-15 04:11 UTC by petersistrom

2023-06-15 04:16 UTC, matthewhilton commented on classes/local/step/flow_web_service.php
> +            'paramslowercase' => ['type' => PARAM_RAW],
Shouldn't this be `PARAM_BOOL` ?

2023-06-15 04:20 UTC, petersistrom commented on classes/local/step/flow_web_service.php
> +            'paramslowercase' => ['type' => PARAM_RAW],
Yes, yes it should! Updated

2023-06-15 06:43 UTC, brendanheywood commented
My preference would be for this not to land. I don't think the original strlower should not have landed and my preference would be for this to be handled as a new expression helper here:

https://github.com/catalyst/moodle-tool_dataflows/blob/9c3ce2e55ab78b03b00306de260a23e474893720/classes/local/provider/expression_provider.php#L68

This means you could selectively lowercase (or uppercase) specific vars as you need to.

@marcghaly I appreciate this may affect you, we could write an upgrade script to try and fix the steps that do this but if there is only a small number of cases in the wild using this it might be better to manually fix these and pretend it was never there.

Happy to hear arguments on the other side of the fence :)

2023-06-15 06:44 UTC, brendanheywood requested changes
See comment:

https://github.com/catalyst/moodle-tool_dataflows/pull/782#issuecomment-1592456653

2023-06-16 00:28 UTC, petersistrom commented
I've updated the patch to use the expression provider. @marcghaly Could you please let us know your thoughts and how it will affect existing flows?

2023-06-16 01:33 UTC, keevan commented on classes/local/step/flow_web_service.php
>          // If password is need will throw exception.
Hi, could we also clean up this comment as I'm not sure how this would happen. Is this still relevant? Does this comment belong here?

Thanks!

2023-06-21 00:28 UTC, petersistrom commented on classes/local/step/flow_web_service.php
>          // If password is need will throw exception.
I've removed the comment, not sure what it is referring to. I agree doesn't look like it belongs there.

2023-06-23 04:43 UTC, petersistrom commented
Hi @brendanheywood Just a bump on this one, hoping to get it merged in soon. Do you think there is anything else required to get it merged?

2023-07-05 02:10 UTC, brendanheywood approved these changes

2023-07-13 23:44 UTC, merged