tweak logging
catalyst/moodle-tool_dataflows pull request #904
Opened 2024-10-10 02:50 UTC by keevan

- **fix: log step to add context to each log message**
- **feat: add min log levels**
- **fix: phpcs fixes**

2024-10-14 03:05 UTC, Peterburnett commented on classes/local/execution/engine.php
> +     * @return void
Void returns are apparently just for returns with an explicit return statement.

https://moodledev.io/general/development/policies/codingstyle#phpdoc

2024-10-14 03:06 UTC, Peterburnett commented on classes/local/execution/engine.php
> +     * @param ?\Throwable $reason A throwable representing the reason for abort.
You have \Throwable in the type, but also import it. Can probably just remove the use

2024-10-14 03:09 UTC, Peterburnett commented on db/install.xml
> +        <FIELD NAME="minloglevel" TYPE="int" LENGTH="1" NOTNULL="false" DEFAULT="100" SEQUENCE="false"/>
Length 1 Default 100 seems wrong right? length was the digit count I though. Unless its bytes?

2024-10-14 03:11 UTC, Peterburnett commented on tests/local/execution/tool_dataflows_engine_test.php
> +    public static function dataflow_provider(): array {
Is this being called statically? Not sure where this comes from, just checking

2024-10-14 03:12 UTC, Peterburnett commented on tests/tool_dataflows_append_file_step_test.php
> +    public static function has_sideeffect_provider(): array {
Is this a new requirement of PHPUnit to make data providers static?

2024-10-14 04:03 UTC, Peterburnett commented
There is a test failure as well about a non matching list of params.

2024-10-14 04:04 UTC, Peterburnett requested changes
Test fail needs to be fixed

2024-10-14 04:10 UTC, keevan commented on classes/local/execution/engine.php
> +     * @return void
Yeah, the strange thing is that those were flagged in the codechecker ci locally and was an autofix..

I'll check it out again and see if it doesn't need to be there. I normally don't include them.

2024-10-14 04:11 UTC, keevan commented on db/install.xml
> +        <FIELD NAME="minloglevel" TYPE="int" LENGTH="1" NOTNULL="false" DEFAULT="100" SEQUENCE="false"/>
Good catch, it should be 2 since it can go up to 900. (It's bytes)

2024-10-14 04:13 UTC, keevan commented on tests/local/execution/tool_dataflows_engine_test.php
> +    public static function dataflow_provider(): array {
Coming from local codechecker ci.

Don't have the output anymore but non-static providers are deprecated since they should be static.

2024-10-14 04:13 UTC, keevan commented on tests/local/execution/tool_dataflows_engine_test.php
> +    public static function dataflow_provider(): array {
It's a php test function dataprovider, so it's defined in the @dataProvider attribute of the php docs for the test.

2024-10-14 04:13 UTC, keevan commented on tests/tool_dataflows_append_file_step_test.php
> +    public static function has_sideeffect_provider(): array {
Yes, it's being deprecated, just staying ahead of the curve.

2024-10-15 22:15 UTC, keevan commented on tests/local/execution/tool_dataflows_engine_test.php
> +    public static function dataflow_provider(): array {
Similar deprecation warning emitted for https://github.com/symfony/symfony/issues/48281

Unable to reproduce now but it was there at one point.

2024-10-15 23:21 UTC, Peterburnett approved these changes

2024-10-15 23:21 UTC, merged